### ISSUE TITLE
Package android.support.v4.content does not exist

### ISSUE THREAD

**Issue by Arsyad** [dpa99c/cordova-plugin-firebase#33] opened 2019-07-05 07:56 UTC
**Describe the bug**
After installing cordova-plugin-firebasex in my Ionic project and trying to compile, it returns a lot of errors as per title.

I am guessing it is something to do with the support library after installing cordova-plugin-firebasex? Is there something I am not doing right

**Console Logs**
```
UnhandledPromiseRejectionWarning: Error: /Users/arsyad/MyApp/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/arsyad/MyApp/platforms/android/app/src/main/java/org/apache/cordova/camera/CameraLauncher.java:64: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
/Users/arsyad/MyApp/platforms/android/app/src/main/java/org/apache/cordova/camera/CordovaUri.java:25: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
/Users/arsyad/MyApp/platforms/android/app/src/main/java/org/apache/cordova/camera/FileProvider.java:21: error: package android.support.v4.content does not exist
public class FileProvider extends android.support.v4.content.FileProvider {}
                                                            ^
/Users/arsyad/MyApp/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:35: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
```

**Plugin Version**
```
cordova-android-firebase-gradle-release 4.0.0 "cordova-android-firebase-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoapod-supportx 1.7.3 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebasex 3.0.8 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Desktop (please complete the following information):**
```
ionic info

Ionic:

   ionic (Ionic CLI)  : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 15 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/arsyad/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 3.1.1
   NodeJS            : v9.4.0 (/usr/local/bin/node)
   npm               : 6.7.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```
My project.properties in platforms/android:

```
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.squareup.okhttp3:okhttp-urlconnection:3.10.0
cordova.system.library.2=com.android.support:support-v4:24.1.1+
cordova.gradle.include.1=cordova-plugin-firebasex/myapp-build.gradle
cordova.system.library.3=com.google.android.gms:play-services-tagmanager:17.0.0
cordova.system.library.4=com.google.firebase:firebase-core:17.0.0
cordova.system.library.5=com.google.firebase:firebase-messaging:19.0.0
cordova.system.library.6=com.google.firebase:firebase-config:18.0.0
cordova.system.library.7=com.google.firebase:firebase-perf:18.0.0
cordova.system.library.8=com.google.firebase:firebase-auth:18.0.0
cordova.system.library.9=com.crashlytics.sdk.android:crashlytics:2.10.1
cordova.system.library.10=com.crashlytics.sdk.android:crashlytics-ndk:2.1.0
cordova.system.library.11=me.leolin:ShortcutBadger:1.1.22
cordova.gradle.include.2=cordova-plugin-mauron85-background-geolocation/myapp-logtofile.gradle
cordova.system.library.12=com.google.android.gms:play-services-location:11+
cordova.system.library.13=com.android.support:support-v4:26+
cordova.gradle.include.3=cordova-android-support-gradle-release/myapp-cordova-android-support-gradle-release.gradle
cordova.gradle.include.4=cordova-android-firebase-gradle-release/myapp-cordova-android-firebase-gradle-release.gradle
```

**Comment by dpa99c** [comment] 2019-07-05 08:24
Duplicate of #29

**Closed by dpa99c** 2019-07-05 08:24 UTC
